services:
  - type: web
    name: nexus-marketplace
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn marketplace_server:app
    envVarGroups:
      - evg-d4n466shg0os73cc41t0
